# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("user.proto", :syntax => :proto3) do
    add_message "user.UserRequest" do
      optional :id, :uint32, 1
    end
    add_message "user.UserResponse" do
      optional :user_name, :string, 1
    end
  end
end

module User
  UserRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("user.UserRequest").msgclass
  UserResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("user.UserResponse").msgclass
end
